## Project: 
Test Numpy
### File: 
Test_Numpy.ipynb
## Author: 
Mobin Yousefi (GitHub: github.com/mobinyousefi-cs)
### Created: 
2025-10-26
### Updated: 
2025-10-26
## Description:
:D
### Usage:
personal tests.

# Numpy(numerical python)
offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

In [3]:
import numpy as np

 ## let's do some basic stuff

In [4]:
a = np.array(5)
a

array(5)

In [14]:
a = np. arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
a.shape

(15,)

In [16]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
a.shape

(3, 5)

In [18]:
a.ndim

2

In [19]:
a.size

15

In [20]:
a.dtype

dtype('int32')

In [21]:
b = np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
b = b.reshape(2,5,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [24]:
b.shape

(2, 5, 2)

In [25]:
b.ndim

3

In [26]:
b.size

20

In [27]:
b.dtype

dtype('int32')

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## some operations

In [31]:
c = np.array([20, 30, 40, 50])
d = np.arange(4)

In [32]:
d

array([0, 1, 2, 3])

In [33]:
c

array([20, 30, 40, 50])

In [36]:
c - d

array([20, 29, 38, 47])

In [37]:
c + d

array([20, 31, 42, 53])

In [38]:
c * d

array([  0,  30,  80, 150])

In [39]:
e = c * d

In [40]:
c > 50

array([False, False, False, False])

In [41]:
e > 50

array([False, False,  True,  True])

In [42]:
np.sin(c)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [43]:
np.sin(e)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])

## End